### ISSUE TITLE
size of gui 

### ISSUE THREAD

**Issue by captain-sensible** [endeavouros-team/PKGBUILDS#110]
reflector-simple on vanilla Arch not working - i've got it working by updating the makepkg. However on testing i can resize the shell window that launches reflector-simple,  but not the GUI of reflector-simple that comes up. On top left of gui there is a mini menu of resize, but it doesn't work. The gui is ok but too large to see the "ok" botton on bottom. i.e i can click in Countries but not actually run it , if that makes sense. Any ideas 

update i got around it by shifting gui upwards using alt + F7 - it worked but a nice resize option would be great

**Comment by killajoe** [comment]
This is an issue with YAD EndeavourOS uses a patched version that is fixing this issue:
you can see in dep tree:
eos-bash-shared is a dep of reflector-simple and it has yad-eos as a dependency.. 
https://github.com/endeavouros-team/PKGBUILDS/tree/master/yad-eos
