### ISSUE TITLE
reflector-simple: Built for Arch and any Arch based distros

### ISSUE THREAD

**Issue by trymeouteh** [endeavouros-team/PKGBUILDS#114]
Please build reflector-simple for Arch and any Arch based distros (Not EndeavorOS or built for a specific distro). This way anyone can install reactor-simple on any Arch based distro and easily manager their mirrors.

**Comment by manuel-192** [comment]
As it has certain common parts with other EndeavourOS software, we are not going to break it.
But it is open source, so anybody is free to replace the common parts with something else, and add it to e.g. AUR.
In fact a version of it is already in AUR: https://aur.archlinux.org/packages/reflector-simple.
