### ISSUE TITLE
eos-update-notifier pre past execute command

### ISSUE THREAD

**Issue by Tealk** [endeavouros-team/PKGBUILDS#134]
Hello,

it would be great if in the config would be a variable for commands to be executed before or after the update.

For example, you could use timeshift to create a snapshot.

**Comment by Tealk** [comment]
Regarding my comment

https://github.com/endeavouros-team/PKGBUILDS/pull/135

I would try to write this from scratch. Would it be interesting for you to get that then?

https://github.com/koalaman/shellcheck
Also gives 300 warnings and some errors

**Comment by manuel-192** [comment]
If you get e.g. the flatpak related problem solved and find a way to modify the code structure so that *only* when we know there will be updates, the pre-command would be executed, then it will be interesting.

However, I think the amount of work for doing that is rather big, so it might be reasonable to think of other alternatives as well.

**Comment by Tealk** [comment]
yes it will be a longer script, but i think it would not be that hard to build the whole thing

I already have an administration script from which I can take a few things.

the with flatpak is grad rather the problem that I still have to test how I retrieve updates without updating them directly.

**Comment by killajoe** [comment]
there are pacman hooks that can do this easily:
https://aur.archlinux.org/packages/timeshift-autosnap/

**Comment by Tealk** [comment]
I'll start now, when it's ready I'll make a pr and then you can decide what you want to do with it.
https://github.com/Tealk/PKGBUILDS/blob/rewrite/eos-update-notifier/eos-update-notifier

**Comment by Tealk** [comment]
One thing I don't quite understand, when I click on the notification, how does the script know that and start the update process?

**Comment by manuel-192** [comment]
Please let's continue this discussion in the EndeavourOS forum. It is much easier to do there.
