### ISSUE TITLE
os-release needs doublequotes insted of singlequotes

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/PKGBUILDS#159]
https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-hooks/eos-hooks-runner
![2021-12-28_14-05](https://user-images.githubusercontent.com/16797647/147569267-dcb0fc43-2a71-4330-9322-d8bb56161adb.png)

```
Example 1. os-release file for Fedora Workstation

NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
https://www.freedesktop.org/software/systemd/man/os-release.html

This is happening for XFCE4 about and also on Plasma About  system info output. 

![2021-12-28_21-51](https://user-images.githubusercontent.com/16797647/147608818-39f14d9d-793a-4a1f-90a8-b16fc9fe6aef.png)
![2021-12-28_21-49_1](https://user-images.githubusercontent.com/16797647/147608821-bfb22286-2a30-4667-a96c-fefc704be6ec.png)

**Comment by TruncatedDinosour** [comment]
fixed in #158

**Comment by killajoe** [comment]
https://gitlab.xfce.org/xfce/libxfce4ui/-/issues/47
As it is allowed to use both single and double quotes by the source i fill an issue at xfce4 source for the app.

**Comment by manuel-192** [comment]
This is an issue with other programs.
But I did remove some single quotes.
