### ISSUE TITLE
Bad Replacement when Removing nvidia drivers on nvidia-installer-dkms

### ISSUE THREAD

**Issue by brunodOut** [endeavouros-team/PKGBUILDS#181]
After running the `nvidia-installer-dkms` with the `-n` option to restore the nouveau driver, I got the output that the `mkinitcpio -p linux` command returned nonzero suggesting to run it manually.

I did ran it manually and got the following errors in the process:
```
==> ERROR: module not found: `_modeset'
==> ERROR: module not found: `_uvm'
==> ERROR: module not found: `_drm'
```

The following code segment is responsible for the problem, as the nvidia modules are prefixed with `nvidia_modname`:
```
nvidia-installer-dkms/nvidia-installer-dkms:
lines 369-381:
------------------------------------------------------------------------------------------------------------------
        # Remove nouveau and nvidia from MODULES line (just in case)
        if line.startswith("MODULES"):
            if "nouveau" in line or "nvidia" in line:
                old_line = line
                line = line.replace("nouveau", "")
                line = line.replace("nvidia", "")
                line = line.replace(",,", ",")
                line = line.replace('",', '"')
                line = line.replace(',"', '"')
                msg = "{0} will be changed to {1} in {2}"
                log_info(msg.format(old_line.strip("\n"), line.strip("\n"), mkinitcpio_path))
                modified = True
        new_mklines.append(line)
```

I have no knowledge on the need for this step (the comment makes me think it might not be needed), but in case it's needed I could implement a small parsing routine to get an array from the value of the `MODULES` variable, and then change the code approach to parse the line and remove any value starting with `nvidia_` prefix. But first I need to understand whether the underlying logic in the current code is correct. 

Shouldn't the code keep (or even add) the nouveau to the modules list in my specific use-case? Or keep/add the nvidia modules when the opposite is done?

Also, making a copy of the changed files before editing and maybe having a verbose argument to show the diff after changing would be quite important IMO! I could help in my free time, even though I'm no python expert.

**Comment by manuel-192** [comment]
Thanks for the report!
This is a known problem. We are currently in the process of replacing nvidia-installer-dkms with a new program **nvidia-inst**.
If possible, you could test that new program and see if it works for you. Note however that it is still in beta level.

To get help about it, run command
```
nvidia-inst -h
```

**Comment by brunodOut** [comment]
Hello!

Sounds great, I'm gonna take a look.

I can create a chroot to run it if it's gonna help with testing! 

Also, do you have a contribution guideline, and also some mailing list where development of EndeavourOS is discussed? Anything like that? I would like to contribute in my spare time.

**Comment by manuel-192** [comment]
Best place to discuss both development and other stuff is the EndeavourOS forum, https://forum.endeavouros.com. For example https://forum.endeavouros.com/c/arch-based-related-questions/community-contributions is an area where contributions like code snippets and tutorials etc. can be done.

Happy to hear about your enthusiasm to help all of us! :+1:
