### ISSUE TITLE
Error on sudo grub-mkconfig -o /boot/grub/grub.cfg

### ISSUE THREAD

**Issue by Jack8472** [endeavouros-team/PKGBUILDS#190]
https://github.com/endeavouros-team/PKGBUILDS/blob/31d14f373b450d6da00e199dbb58214e44fe769f/grub-tools/eos-grub-fix-initrd-generation#L72

I think this causes this error when `sudo grub-mkconfig -o /boot/grub/grub.cfg`: 

> /etc/grub.d/30_os-prober: 222: Syntax error: "(" unexpected (expecting "fi")

I am not a programmer but I think this can be corrected by substituting `LINITRD=($LINITRD);` with `LINITRD=$LINITRD;`

**Comment by manuel-192** [comment]
Thanks for the report.
Can't reproduce it here, so we need more information, like the contents of the resulting 30_os-prober file and more.
The best place to discuss this is our forum:
https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports

**Comment by Jack8472** [comment]
I cannot reproduce at the moment as I have to work on the system I fixed as shown above.

However, `LINITRD=($LINITRD);` is just bad shell syntax, parenthesis are reserved  for commands and cannot have solely a variable inside (i guess).

**Comment by manuel-192** [comment]
You should learn bash before making false statements.
Let's continue this discussion on the EndeavourOS forum.
