### ISSUE TITLE
Poor quality of Romanian translations

### ISSUE THREAD

**Issue by georgeabr** [endeavouros-team/PKGBUILDS#22]
For example in file ` PKGBUILDS/welcome/translations-welcome-ro.bash`:  
EN `site` should be RO`sit/situri`, not the the Romglish `site-uri`.
The word itself is of Latin origin, and the Romanian equivalent does not need this horrible anglicization.

Missing space between two sentences separated by a full stop (not a showstopper, but sill):  
`este dezactivată.Pentru a o`

Generic terms could be translated in target language, even if the original term is understood by non-English users.
For example I would translate `Display Manager` by `Gestionar de afișaj`.
`Web Browser` could be translated as `Navigator Internet`.

Double space after the word Arch - `Utilizator Arch  și`.
English `-ing` forms, which have a continuous meaning (something is in progress), have been butchered by using the corresponding Romanian gerund, which sounds hilarious and robotic, unnatural.
If you want to state that you're currently doing something, in Romanian you can use a noun:
`Executând comenzi` should be `Execuție comenzi`, or, by imitating French, `Comenzi în curs de execuție`.
Lots of `-ing` form mistranslations to be corrected.

Missing Romanian diacritics: `Actualizari de la` should be `Actualizări de la`.
The translator should use a Romanian spell-checker to correct words, when translating. Firefox has one, with Romanian language as an option.

Mistranslation of the English `location` - `locații de descărcare`. Stop using the Romanian `locație` as an equivalent to English `location`.
Use the Romanian `destinație`, `loc`, `punct de descărcare`.
In English, these words are called `false friends`, same word in both languages, but with different meanings.

**Comment by FLVAL** [comment]
Thank You for your Comment but first I would like to tell you that a big part of the translate you did doesn't enter in our BUTTON on the App, so we use words without article in our BUTTON then full sentence with articles appears on the TOOLTIP which appears on rollover and this change already your way to translate !

But I will bring your proposal to @Anticupidon who works on it to see if some of them could make it better.

Cordially

**Comment by manuel-192** [comment]
Please report issues at: https://forum.endeavouros.com because some of the translators may not notice reports here.
