### ISSUE TITLE
ly can not build

### ISSUE THREAD

**Issue by gnuhub** [endeavouros-team/PKGBUILDS#245]

**Comment by manuel-192** [comment]
EndeavourOS takes ly as-is from the AUR. The issue has been reported there.
Looks like ly-git builds OK.

**Comment by killajoe** [comment]
Thank you for the great support, we could really use your help! @gnuhub 

@manuel-192 we should simple remove it completely for now.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/PKGBUILDS/commit/91d1773eb23acebdb4a8914f79f94a2da2d01887
