### ISSUE TITLE
PGP signiture error on nvidia-hook

### ISSUE THREAD

**Issue by zadobudak** [endeavouros-team/PKGBUILDS#249]
when I try to update the packages, I get this error I think it has to do with Nvidia-hook and there was a change 10hours ago so that's all .

tried recreating keyrings and also deleting /var/cache/pacman/pkg/nvidia-hook-1.2-1-any.pkg.tar.zst file. 

`: Proceed with installation? [Y/n] Y

:: Retrieving packages...

 nvidia-hook-1.2-1-any                     13,6 KiB  26,8 KiB/s 00:01 [---------------------------------------] 100%

 (33/33) checking keys in keyring                                      [---------------------------------------] 100%

 (33/33) checking package integrity                                    [---------------------------------------] 100%

 error: nvidia-hook: signature from "EndeavourOS <info@endeavouros.com>" is unknown trust

 :: File /var/cache/pacman/pkg/nvidia-hook-1.2-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

 Do you want to delete it? [Y/n] 

 error: failed to commit transaction (invalid or corrupted package)

 Errors occurred, no packages were upgraded.
 `

**Comment by manuel-192** [comment]
Do you have the required package `endeavouros-keyring` installed?
Uninstall nvidia-hook if it is installed: `sudo pacman -R nvidia-hook`
Delete all nvidia-hook related files from the package cache.
Run `sudo pacman -Syyu nvidia-hook`

**Comment by zadobudak** [comment]
Thanks for your fast response I found the problem once my keyrings were messed up and re created the masterkeyring list however I didn't see the need of using `sudo pacman-key --populate archlinux **endeavouros**` just used archlinux and because of that even though the `endeavouros-keyring` was installed I was not able to install from eos. 
This article helped me solve the problem: [https://discovery.endeavouros.com/signature-and-keyring/pacman-keyring-issues/2021/03/](url)
