### ISSUE TITLE
Surprising version number for `eos-translations`

### ISSUE THREAD

**Issue by ziw-liu** [endeavouros-team/PKGBUILDS#254]
When updating my system I found that the version number for `eos-translations` has not incremented, but leaped 22 major versions:

```log
Package (18)                  Old Version       New Version       Net Change  Download Size

endeavouros/eos-translations  1.22-1            23-2                0.02 MiB       0.07 MiB
```

And this is likely a typo introduced in [this commit](https://github.com/endeavouros-team/PKGBUILDS/commit/906b243292a4645fcbd8a3fbd062f2b85690bbf8), as the [previous change to that line](https://github.com/endeavouros-team/PKGBUILDS/commit/c9117f4c8775073b2c0f0c87893146a8230906dc) bumped the minor version from `1.21` to `1.22`.

**Comment by manuel-192** [comment]
Thanks for the report!
However it is not a typo but a change in the versioning scheme.
