### ISSUE TITLE
reflector-simple default window too large on some displays

### ISSUE THREAD

**Issue by 0pcom** [endeavouros-team/PKGBUILDS#259]
When reflector-simple is invoked from the eos-welcome app on machines connected to displays which are running at lower resolutions, the window is larger than the displayed area.

this could be fixed if the checkbox with the text `Bosnia and Herzegovina` was at the end of a row, or if the text would wrap to the next line for that entry.

**Comment by 0pcom** [comment]
Also, it would be ideal when displaying the new mirrorlist, prompting the user to save, if it was able to be edited as it is being displayed

**Comment by manuel-192** [comment]
Have you tried to adjust related settings in file `/etc/reflector-simple-tool.conf`?
The settings and their default values are:
```
REFLECTOR_SIMPLE_COLUMNS=5
REFLECTOR_SIMPLE_WIDTH=1000
REFLECTOR_SIMPLE_HEIGHT=750
```
If they make any helpful difference, please let me know.

**Comment by manuel-192** [comment]
Please note that the best place to discuss the EndeavourOS tools is the forum (https://forum.endeavouros.com/).
