### ISSUE TITLE
Warning abaut translation

### ISSUE THREAD

**Issue by Davidmp1** [endeavouros-team/PKGBUILDS#260]
When clicking on Update system on the Welcome app, this warning message appears: 
Info: translation issues detected, see file '/tmp/translations-7yRtc.errlog'

The tmp file states this:
Warning: Welcome: language 'ca' placeholder 'nb_nofify_user1': translation not found, 'en' used as fallback.

But the rest of the text of the update system option and everything else in the Welcome app is correctly displayed in Catalan, so the translation is working fine.

I am the translator of the file translation-ca.bash and I wanted to ask if I missed something to change in the file or it is something that needs to be changed elsewhere.

Thanks!

**Comment by killajoe** [comment]
```
# 2022-Sep-25
_tr_add2 nb_nofify_user1             "There is important news at"
_tr_add2 nb_nofify_user2             "Please click the"                                  # Software News
_tr_add2 nb_nofify_user3             "button at the low left corner of this window."
```
is not present in the ca file ;)

**Comment by killajoe** [comment]
b.t.m. you can add the lines to the file and translate it to Katalan new translations are not merged in the translations automatically.

**Comment by Davidmp1** [comment]
Ok, thank you very much. I thought it was another kind of issue!
