### ISSUE TITLE
Update EndeavourOS mirrors can't connect to https://endeavour.remi.lu/repo/$repo/$arch

### ISSUE THREAD

**Issue by unsermanninchina** [endeavouros-team/PKGBUILDS#265]
Updating the EndeavourOS mirrors can't get one of the repositories: https://endeavour.remi.lu/repo/$repo/$arch

Online I can find the mirror here:
https://de.freedif.org/EndeavourOS/repo/endeavouros

Is the link in the config file wrong?

Thank you!

**Comment by killajoe** [comment]
https://endeavour.remi.lu/repo/endeavouros/x86_64/
i can reach it... 

> Online I can find the mirror here:
> https://de.freedif.org/EndeavourOS/repo/endeavouros

this is another mirror.. but you replaced _$repo_ with the reponame there so you can find the files ?
