### ISSUE TITLE
[BROKEN] nvidia-driver-supported-branches

### ISSUE THREAD

**Issue by ManuLinares** [endeavouros-team/PKGBUILDS#269]
This script https://github.com/endeavouros-team/PKGBUILDS/blob/master/nvidia-installer-common/nvidia-driver-supported-branches is broken.

output:

```
NVIDIA card id: 2484
Fetching driver data from nvidia.com ...
nvidia-driver-supported-branches: error: Nvidia id data not available from 'https://us.download.nvidia.com/XFree86/Linux-x86_64/525.89.02
525.89.02
525.89.02/README/supportedchips.html'! Curl exit code 3.
```

Even if I remove the "us." from the url, it fails

**Comment by killajoe** [comment]
https://download.nvidia.com/XFree86/Linux-x86_64/525.89.02/README/supportedchips.html

strange.. 

@manuel-192  would know better.. the urls changing from time to time.

**Comment by dalto8** [comment]
It looks to me like the version is being injected more than once.

Likely the below line is problematic if you have multiple repos containing `nvidia-dkms`

https://github.com/endeavouros-team/PKGBUILDS/blob/master/nvidia-installer-common/nvidia-driver-supported-branches#L202

**Comment by ManuLinares** [comment]
> It looks to me like the version is being injected more than once.
> 
> Likely the below line is problematic if you have multiple repos containing `nvidia-dkms`
> 
> https://github.com/endeavouros-team/PKGBUILDS/blob/master/nvidia-installer-common/nvidia-driver-supported-branches#L202

Indeed I do have more than one repo with "nvidia-dkms"

**Comment by manuel-192** [comment]
Thanks for the report and all comments!

@ManuLinares 
New version 23-2 of package `nvidia-installer-common` should fix this, please try it and report the result.

**Comment by ManuLinares** [comment]
Thanks, there is the same bug in file `nvidia-inst` in line 539

`local latest_from_arch=$(LANG=C pacman -Si nvidia-dkms | grep -w ^Version | awk '{print $3}' | cut -d '.' -f1)`

**Comment by manuel-192** [comment]
Thanks again, I'll change `nvidia-inst` accordingly.

About the hook: unfortunately we do not support AUR packages.
But of course you can add those lines manually, although you'd need to add them again after every update of `nvidia-hook`. But this package likely won't be updated often.
