### ISSUE TITLE
Potential New Public Mirror

### ISSUE THREAD

**Issue by TechCiel** [endeavouros-team/PKGBUILDS#270]
Hi maintainers of the EndeavourOS,

I'm the operator of the open-source mirrors at Jilin University, China. I've got some requests from students recently for an EndeavourOS mirror, so I'm going to do that. I didn't, however, see any guidance for mirroring this distro. I'd like to know:

1. Do you welcome new public mirror for this project?
2. Are the resources in the repository all redistributable?
3. What's the rsync (or something else) endpoint for mirroring?
4. How often should I schedule the sync task?
5. Do you have a mail list (or something else) for mirrors?

The mirrors will be available on https://mirrors.jlu.edu.cn. Please note in the meantime, only IPv6 is accessible on the Internet, but the IPv4 will be open soon.

Thanks for your time and attention!

**Comment by killajoe** [comment]
@AlpixTM @manuel-192 
.. we can also change to use a repo dedicated for mirrors.. would make it more clean...

**Comment by AlpixTM** [comment]
Hey,

thank you for your generous offer.

Could you please write me an email to alpix[ät]endeavouros.com?

**Comment by TechCiel** [comment]
Hi @AlpixTM,

> Could you please write me an email to alpix[ät]endeavouros.com?

I've sent a copy of this issue via mirrors[ät]jlu.edu.cn, please kindly remember to check spam box.

**Comment by killajoe** [comment]
will get on the list soon.
