### ISSUE TITLE
Weird string in Welcome

### ISSUE THREAD

**Issue by zica87** [endeavouros-team/PKGBUILDS#271]
https://github.com/endeavouros-team/PKGBUILDS/blob/1053b5cd3c05c3ba6e482e7df88690b832cb2c97/eos-translations/translation-en.bash#L272

I see in the actual app there is `meld` after the above string.
Why not put the word in the string?
It makes the syntax of the translation weird.

**Comment by manuel-192** [comment]
The app name is configurable by a user and will be added by the Welcome app in the end of that line.
That's why you'll see, by default, `meld` in the end.

**Comment by zica87** [comment]
Alright.
The translation would be weird then.
