### ISSUE TITLE
eos-reboot-required: App name for notification is unset

### ISSUE THREAD

**Issue by EbonJaeger** [endeavouros-team/PKGBUILDS#272]
Budgie Desktop (and probably other desktop environments) shows the application name when displaying notifications, which in the case of `eos-reboot-required` is unset, defaulting to "notify-send". It may be desirable to pass in an app name to `notify-send` when sending the notification.

**Comment by manuel-192** [comment]
Thanks!
The app name will be added in the next release of package `eos-hooks`.
