### ISSUE TITLE
nvidia-inst legacy drivers: add hint about kernel-lts repo

### ISSUE THREAD

**Issue by plata** [endeavouros-team/PKGBUILDS#275]
When trying to install legacy drivers (e.g. 390), it correctly notifies to use the AUR packages with yay (as does the [Discovery entry](https://discovery.endeavouros.com/nvidia/new-nvidia-driver-installer-nvidia-inst/2022/03/)).

However, in my case the kernel-lts repository was still enabled in `pacman.conf` and the wrong drivers got installed. It took some time to realize this because the driver was somewhat working but with very poor performance.

I noticed that the latest EndeavourOS `pacman.conf` doesn't contain kernel-lts anymore. Is this even maintained now that Jonathon passed away? At least it's still listed in the Arch wiki.

I think it would be a good idea to add a note to Discovery and nvidia-inst that kernel-lts should be removed.

**Comment by manuel-192** [comment]
Thanks for the report!

Adding the `kernel-lts` repo was an additional feature of the `nvidia-inst` program.
`kernel-lts` is not (and never was) included as one of the default repos in `pacman.conf`.

Now that the status of the `kernel-lts` repo is no more clear, we decided some time ago *not* to add it using option `--legacyrepo` in `nvidia-inst`; using this option causes a warning about the repo and stops execution. In addition, we recommend not to use `kernel-lts` as long as the status is like this.

We can add the notes about removing that repo, and hope that users will read the notes.

**Comment by plata** [comment]
> We can add the notes about removing that repo, and hope that users will read the notes.

+1

For my understanding: Is there a particular reason why `nvidia-inst` doesn't just run `yay` directly?

**Comment by dalto8** [comment]
> For my understanding: Is there a particular reason why `nvidia-inst` doesn't just run `yay` directly?

Before installing anything from the AUR, we want people to understand the risks and considerations and make a decision to take that path.

If we automate it, too many people will just blindly hit Y.
