### ISSUE TITLE
nvidia-inst: add NVIDIA's open-gpu-kernel-modules as option

### ISSUE THREAD

**Issue by notjl** [endeavouros-team/PKGBUILDS#286]
I noticed that the installer doesn't have support for the open GPU kernel modules from NVIDIA. It would be great if it was one of the options people can opt for when installing NVIDIA drivers.

**Comment by manuel-192** [comment]
Thanks for bringing this up!
I plan to add an option that installs nvidia-open-dkms instead of nvidia-dkms.
I assume this is what you meant.
May take some time though, but hopefully I can squeeze some time to implement it during this month.

**Comment by manuel-192** [comment]
Added option `--open` for this.
