### ISSUE TITLE
"Welcome" app is not translated when launched with Live Image.

### ISSUE THREAD

**Issue by FuRuYa7** [endeavouros-team/PKGBUILDS#309]
### "Welcome" app is not translated when launched with Live Image.

I made a script to translate:

Feel free to modify it.

Set script to autostart when booting with Live Image. Since it is related 
to system design, I submitted it as "Issues" instead of "Pull requests".

#### 2). Create a "Language List Menu" using yad:

```
sudo xed /usr/share/endeavouros/scripts/live-LANG-select-menu
```

```
#!/bin/bash

yad --list\
      --column="Language:":TEXT\
      --column=" ":TEXT\
      --separator="/"\
      --width=400 --height=500\
      --title="Select language for 'Welcome'" --fontname="Mono 10"\
      English en_US\
      Catalan（català） ca_AD\
      German（Deutsch） de_DE\
      Spanish（Español・Española） es_ES\
      Persian（فارسی） fa_IR\
      Finnish（Suomalainen） fi_FI\
      French（Francés・Francesa） fr_FR\
      India（हिंदी-भारत） hi_IN\
      Croatian（Hrvatski） hr_HR\
      Icelandic（Íoslainnis） is_IS\
      Italian（Italiano・Italiana） it_IT\
      Japanese（日本語） ja_JP\
      Polish（Polski） pl_PL\
      Portuguese（Português） pt_PT\
      Portuguese-Brazil（Português-Brasil） pt_BR\
      Romanian（Română） ro_RO\
      Russian（Русский） ru_RU\
      Norway（Norge） se_NO\
      Slovak（slovenský） sk_SK\
      Thai（แบบไทย） th_TH\
      Ukrainian（українська） uk_UA\
      Chinese-China（中文-中国） zh_CN\
      Chinese-HongKong（中文-香港） zh_HK\
      Chinese-Singapore（中文-新加坡） zh_SG\
      Chinese-Taiwan（中文-台灣） zh_TW

```

Note: The language used in "translation-rs.bash" seems to be "Croatian", 
but I excluded it because there is no comment line (country code) 
in "/etc/locale.gen".

#### 3). Create the main script:

```
sudo xed /usr/share/endeavouros/scripts/live-LANG-select
```

```
#!/bin/bash

result=$(bash /usr/share/endeavouros/scripts/live-LANG-select-menu | cut -d/ -f2)
echo "en_US.UTF-8 UTF-8" > locale.${result}
echo ${result}".UTF-8 UTF-8" >> locale.${result}
sudo cp locale.${result} /etc/locale.gen
sudo locale-gen
export LANG=$(echo ${result}".UTF-8")
eos-welcome

```

Note: Locale settings are only valid within scripts. However, 
you can start the app by specifying the country code.

#### 4). Set script to autostart when booting with Live Image:

EndeavourOS -> 'Settings' -> 'Session and Startup' -> 'Application Autostart' 

 -> 'Welcome(EndeavourOS Welcome Launcher)' 

```
Command: sh /usr/share/endeavouros/scripts/welcome --startdelay=3 
```

↓ Replace:

```
Command: sh /usr/share/endeavouros/scripts/live-LANG-select --startdelay=3
```

#### 5). FYI: To see how the script works:

```
sh /usr/share/endeavouros/scripts/live-LANG-select
```

##### (1). Language selection menu launches:

![1_select-language-menu](https://github.com/endeavouros-team/PKGBUILDS/assets/46095926/1fce1ebc-da11-4a19-b7d5-f5ea1cd72934)

##### (2). Launch the "Welcome" app in the selected language:

![2_Welcome](https://github.com/endeavouros-team/PKGBUILDS/assets/46095926/2e4fa447-14b5-479a-a993-ab0d463eca0b)

**Comment by FuRuYa7** [comment]
Fixed the auto-starting part of the app after "item number 4).":


---

### "Welcome" app is not translated when launched with Live Image.

I made a script to translate:

Feel free to modify it.

Set script to autostart when booting with Live Image. Since it is related 
to system design, I submitted it as "Issues" instead of "Pull requests".


#### 1). Launch with Live Image:


#### 2). Create a "Language List Menu" using yad:

```
sudo xed /usr/share/endeavouros/scripts/live-LANG-select-menu
```

```
#!/bin/bash

yad --list\
      --column="Language:":TEXT\
      --column=" ":TEXT\
      --separator="/"\
      --width=400 --height=500\
      --title="Select language for 'Welcome'" --fontname="Mono 10"\
      English en_US\
      Catalan（català） ca_AD\
      German（Deutsch） de_DE\
      Spanish（Español・Española） es_ES\
      Persian（فارسی） fa_IR\
      Finnish（Suomalainen） fi_FI\
      French（Francés・Francesa） fr_FR\
      India（हिंदी-भारत） hi_IN\
      Croatian（Hrvatski） hr_HR\
      Icelandic（Íoslainnis） is_IS\
      Italian（Italiano・Italiana） it_IT\
      Japanese（日本語） ja_JP\
      Polish（Polski） pl_PL\
      Portuguese（Português） pt_PT\
      Portuguese-Brazil（Português-Brasil） pt_BR\
      Romanian（Română） ro_RO\
      Russian（Русский） ru_RU\
      Norway（Norge） se_NO\
      Slovak（slovenský） sk_SK\
      Thai（แบบไทย） th_TH\
      Ukrainian（українська） uk_UA\
      Chinese-China（中文-中国） zh_CN\
      Chinese-HongKong（中文-香港） zh_HK\
      Chinese-Singapore（中文-新加坡） zh_SG\
      Chinese-Taiwan（中文-台灣） zh_TW

```

Note: The language used in "translation-rs.bash" seems to be "Croatian", 
but I excluded it because there is no comment line (country code) 
in "/etc/locale.gen".


#### 3). Create the main script:

```
sudo xed /usr/share/endeavouros/scripts/live-LANG-select
```

```
#!/bin/bash

result=$(bash /usr/share/endeavouros/scripts/live-LANG-select-menu | cut -d/ -f2)
echo "en_US.UTF-8 UTF-8" > locale.${result}
echo ${result}".UTF-8 UTF-8" >> locale.${result}
sudo cp locale.${result} /etc/locale.gen
sudo locale-gen
export LANG=$(echo ${result}".UTF-8")
eos-welcome

```

Note: Locale settings are only valid within scripts. However, 
you can start the app by specifying the country code.


#### 4). Set script to autostart when booting with Live Image:

EndeavourOS -> 'Settings' -> 'Session and Startup' -> 'Application Autostart' 



 -> 'Welcome(EndeavourOS Welcome Launcher)' 


```
Command: sh /usr/share/endeavouros/scripts/welcome --startdelay=3 
```


#### 5). Click the "check" at the beginning of the line to remove the check:


#### 6). Click "+ Add" to add:

Name: 

```
Welcome(Translate and launch EndeavorOS welcome)
```

Command:

```
sh /usr/share/endeavouros/scripts/live-LANG-select --startdelay=3
```

Trigger:

```
on login
```

→「Cloxe」


#### 7).Click "liveuser" at the bottom right of the screen:

-> “Log Out...” -> “Log Out”



#### 8). Automatically logged in:


##### (1). Language selection menu launches:

![1_select-language-menu](https://github.com/endeavouros-team/PKGBUILDS/assets/46095926/1fce1ebc-da11-4a19-b7d5-f5ea1cd72934)


##### (2). Launch the "Welcome" app in the selected language:

![2_Welcome](https://github.com/endeavouros-team/PKGBUILDS/assets/46095926/2e4fa447-14b5-479a-a993-ab0d463eca0b)

**Comment by FuRuYa7** [comment]
Typo: →「Cloxe」

-> "Close"

**Comment by manuel-192** [comment]
Thanks! :+1:
In fact this has been something that I simply didn't notice, even though the translations were already designed to support the installer part of welcome too.

I'm planning to use parts of this code in welcome, but will include it a bit later, after the next ISO which should be coming in somewhat near future.

**Comment by FuRuYa7** [comment]
Thank you for considering it ! 

Changed the main "script" to add the selected locale without deleting the contents of "/etc/locale.gen":

---

#### 3). Create the main script:

```
$ sudo xed /usr/share/endeavouros/scripts/live-LANG-select
```

```
#!/bin/bash

result=$(bash /usr/share/endeavouros/scripts/live-LANG-select-menu | cut -d/ -f2)
cp /etc/locale.gen locale.${result}
echo >> locale.${result}
echo "###" >> locale.${result}
echo "#" >> locale.${result}
echo "# Locale used in 'Welcome'" >> locale.${result}
echo "en_US.UTF-8 UTF-8" >> locale.${result}
echo ${result}".UTF-8 UTF-8" >> locale.${result}
sudo cp locale.${result} /etc/locale.gen
sudo locale-gen
export LANG=$(echo ${result}".UTF-8")
eos-welcome

```
