### ISSUE TITLE
`eos-update-notifier` doesn't use `EOS_AUR_HELPER`

### ISSUE THREAD

**Issue by imsuck** [endeavouros-team/PKGBUILDS#310]
`eos-update-notifier` doesn't use `EOS_AUR_HELPER` when `ShowHowAboutUpdates` in `/etc/eos-update-notifier.conf` is set to `notify`.

This can be fixed by changing line 107 in [eos-update-notifier](https://github.com/endeavouros-team/PKGBUILDS/blob/0f5880033744a3c9404f7fc09fded4355201a9d2/eos-update-notifier/eos-update-notifier) to `RunInTerminal eos-update --helper "$EOS_AUR_HELPER"`.
https://github.com/endeavouros-team/PKGBUILDS/blob/0f5880033744a3c9404f7fc09fded4355201a9d2/eos-update-notifier/eos-update-notifier#L106-L109

**Comment by manuel-192** [comment]
Thanks! Fixed and released.
