### ISSUE TITLE
changed versioning 

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/PKGBUILDS#325]
![2024-02-05_01-17](https://github.com/endeavouros-team/PKGBUILDS/assets/16797647/959ebae8-dd07-48d1-8cab-6c9c2e0c7af6)

is this be reason or accident?
https://github.com/endeavouros-team/PKGBUILDS/commit/4315440f9adbeea71c4ef477945898523b54f898

**Comment by flyingcakes85** [comment]
This was brought up by a Reddit user: https://www.reddit.com/r/EndeavourOS/comments/1aikwm6/eosrankmirrors_241/

I told them `24-1` is the intended version as per our PKGBUILD.

**Comment by manuel-192** [comment]
Yes, that was a planned change. I've been changing EOS packages to use this numbering with two-digit **year** as the first number in `pkgver,` and the second `pkgver` number after dot is just a serial number of the change.
I estimate there will not be many changes in most packages within a year, maybe with the exception of `eos-bash-shared` and perhaps `welcome`.

**Comment by killajoe** [comment]
> And after year 2099 the numbering can easily be changed to `2100.x`. ;)

EndeavourOS plans to stay

**Comment by flyingcakes85** [comment]
Manuel got plans to make EnOS the longest running distro 😉
