### ISSUE TITLE
Inclusion of Taiwan as a Separate Region, Not Country

### ISSUE THREAD

**Issue by infopensource** [endeavouros-team/PKGBUILDS#326]
I hope this message finds you well. I am writing to bring to your attention a matter related to the reflector-simple tool, specifically concerning the categorization of countries. Currently, the tool treats China and Taiwan as separate countries, which may lead to inaccuracies.

I kindly request an enhancement to the reflector-simple tool that would recognize Taiwan as a distinct region rather than a separate country. This adjustment aims to align with the sensitivity of geopolitical considerations and adhere to a neutral stance, treating Taiwan as part of a broader region.

The purpose of this request is to foster inclusivity and avoid any potential political implications that may arise from categorizing Taiwan as an independent country. By representing Taiwan as a region within the tool, we can contribute to a more nuanced and politically neutral user experience.

I appreciate your attention to this matter and the continuous effort to improve the Endavouros ecosystem. If you require further clarification or information, please feel free to reach out.

Thank you for your understanding and consideration.

**Comment by infopensource** [comment]
as well as HongKong，maybe you can just replace Country with Region
![image](https://github.com/endeavouros-team/PKGBUILDS/assets/44309311/3a28d5c0-2157-420f-b680-d486e7159201)

**Comment by dalto8** [comment]
reflector-simple is a GUI for reflector.  It is reflector that refers to those entities as countries.

I am not sure that reflector-simple should use different nomenclature than reflector itself does.

Perhaps it would be better to make this request upstream to reflector instead of here?  If it was changed in reflector, that change could naturally propagate to reflector-simple.
