### ISSUE TITLE
[welcome] would it not better to have eos-quickstart optional?

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/PKGBUILDS#327]
https://github.com/endeavouros-team/PKGBUILDS/blob/307640fcd15a4a072616b10e1bce4debfaa9773d/welcome/PKGBUILD#L11

In case users do not need it, they can only remove it with welcome itself.
Would be more convenient to have it optional from my point of view.

**Comment by manuel-192** [comment]
Not sure I follow your logic.
How would it be optional?
And those who don't need it can simply skip it.

**Comment by dalto8** [comment]
I think he is suggesting that you should be able to install welcome without installing eos-quickstart.  Since it is currently a required dependency, it will always get installed with welcome.

If it was an optional dependency, the user could choose to have it or not based on their preference.

**Comment by manuel-192** [comment]
And users who don't know about optional dependencies (and pacman details), how would they be aware of it? 
Note also that some users have said eos-quickstart has been a great addition to welcome.
We simply can't please everyone.

**Comment by manuel-192** [comment]
Sorry guys if I sounded aggressive, it wasn't my intention.
There are some good reasons in changing eos-quickstart as an optional dependency, although I guess some users might complain about it.
So I'll change it to optional as soon as possible.

**Comment by killajoe** [comment]
It will be still installed by default, and users will be able to use it to start their journey. 

https://github.com/endeavouros-team/calamares/blob/1a49c71b0b7e78ac16f2c8321ecae1e35e1bf6b7/data/eos/modules/netinstall.yaml#L149

We could think about creating a group for EndeavourOS helper tools?

But this for another place ;)
