### ISSUE TITLE
Addressing Changes from Arch Git Migration

### ISSUE THREAD

**Issue by lpnh** [endeavouros-team/PKGBUILDS#328]
I was exploring my themes today when I ended up stepping into this broken link: 

https://github.com/endeavouros-team/PKGBUILDS/blob/794f92186901dc016a84b4bf793ea857243adea7/arc-gtk-theme-eos/man/arc-gtk-theme-eos/arc-gtk-theme-eos.md?plain=1#L10

As you can see the link is pointing to a `community` repository, and according with this [announcement](https://archlinux.org/news/git-migration-announcement/), they were merged into the `extra` one.

Probably its current address would be https://archlinux.org/packages/extra/any/arc-gtk-theme/

Because of this, I thought about sending a PR fixing it, so I decided to take a look if there was other broken links that would fall in the same situation, and I also found this one:

https://github.com/endeavouros-team/PKGBUILDS/blob/794f92186901dc016a84b4bf793ea857243adea7/yad-eos/README.md?plain=1#L15

Same thing, probably its current address: https://archlinux.org/packages/extra/x86_64/yad/

Then I saw these two lines during my search:

https://github.com/endeavouros-team/PKGBUILDS/blob/794f92186901dc016a84b4bf793ea857243adea7/eos-hooks/eos-repo-before-arch-repos#L53

https://github.com/endeavouros-team/PKGBUILDS/blob/794f92186901dc016a84b4bf793ea857243adea7/eos-repo-before-arch-repos/eos-repo-before-arch-repos#L53

I don't know if these references might also require updating due to the repository changes. For that reason, I thought opening an Issue would be a more reasonable approach as this goes beyond of simply fixing a broken link.

Hope this could be helpful. Thanks for all the work!

**Comment by dalto8** [comment]
Thanks for reporting this.

For the two README changes, those can be updated easily.

> Then I saw these two lines during my search:

We can probably remove that hook at this point.  It was a transition item but enough time has passed at this point that we shouldn't need it anymore.
