### ISSUE TITLE
Where to find PKGBUILDs for EnOS packages not in this repo?

### ISSUE THREAD

**Issue by hlein** [endeavouros-team/PKGBUILDS#335]
I'm trying to track down the `PKGBUILD` files for all EndeavourOS packages (as part of https://github.com/hlein/distro-backdoor-scanner/issues/2), but when I compare those listed by `pacman -Sl endeavouros` to those in the https://github.com/endeavouros-team/PKGBUILDS repo, there are some packages I can't find:
```
$ pacman -Sl | expac -S '%r|%e|%v' - | sort -u >~/package_list
$ git clone https://github.com/endeavouros-team/PKGBUILDS endeavouros && cd endeavouros
$ for P in $(egrep '^endeavouros\|' ~/package_list | cut -d\| -f2) ; do test -d $P || echo -n "$P " ; done ; echo
arc-gtk-theme bashdb downgrade lxdm mkinitcpio-openswap paru rate-mirrors yay zfs-dkms zfs-utils 
```
There's an `arc-gtk-theme-eos/` so that probably covers that, and there's a `yay.not-used/` so... skip that. but the others...?

I'm new to the Arch / EnOS ecosystem so maybe I'm missing something obvious. Do they maybe live in AUR that I need to look in?

**Comment by manuel-192** [comment]
The "subfolders" of `https://github.com/endeavouros-team/PKGBUILDS` is where the PKGBUILD file for most packages exist. The PKGBUILD files tell where the source code of each package exists, and as you can see, for most packages the source code is in the same "subfolder".

A small number of packages are taken directly from the AUR.

Hope this answers your question.

**Comment by dalto8** [comment]
Where is `lxdm` coming from?  Are we building our own package?

**Comment by hlein** [comment]
> The "subfolders" of `https://github.com/endeavouros-team/PKGBUILDS` is where the PKGBUILD file for most packages exist. The PKGBUILD files tell where the source code of each package exists, and as you can see, for most packages the source code is in the same "subfolder".
> 
> A small number of packages are taken directly from the AUR.
> 
> Hope this answers your question.

Thanks, yeah I should have been clearer: there are some `endeavouros` packages for which no corresponding subdirectory w/a `PKGBUILD` file exists in the https://github.com/endeavouros-team/PKGBUILDS repo. That's what the list of exceptions is: packages for which there's no subfolder. So maybe those missing ones come from AUR?

**Comment by manuel-192** [comment]
Actually some of the packages are modified versions of the Arch packages.
Forgot to mention that in the previous answer, sorry about that.

For example, `yad` has a patch applied to the yad from Arch.

@dalto8 
Probably Joe can tell where `lxdm` is coming from. I assume it is also a modified version of an Arch package.

**Comment by killajoe** [comment]
eos-lxdm-gtk3
Used Sources: 

https://github.com/endeavouros-team/PKGBUILDS/blob/3c44ef03aff744af0045fbfdcf59433c6588a277/eos-lxdm-gtk3/PKGBUILD#L24

https://github.com/endeavouros-team/PKGBUILDS/blob/3c44ef03aff744af0045fbfdcf59433c6588a277/eos-lxdm-gtk3/PKGBUILD#L25

It uses original lxde sources from sourceforge and the added theme from our Github.

**Comment by hlein** [comment]
> eos-lxdm-gtk3 Used Sources:
> 
> https://github.com/endeavouros-team/PKGBUILDS/blob/3c44ef03aff744af0045fbfdcf59433c6588a277/eos-lxdm-gtk3/PKGBUILD#L24

Aha, and I see, in there is `pkgbase=lxdm`. So the directory names in the `PKGBUILDS` repo can be different from the `pkgbase` name.

...But that seems to only explain that one package. Where are the `PKGBUILD` files for the others?
> ~~arc-gtk-theme~~ bashdb downgrade ~~lxdm~~ mkinitcpio-openswap paru rate-mirrors ~~yay~~ zfs-dkms zfs-utils

**Comment by dalto8** [comment]
The rest of those are from AUR.

**Comment by hlein** [comment]
> The rest of those are from AUR.

Thank you! Is there a build recipe or README.md somewhere that I should've found, that specifies that?

**Comment by manuel-192** [comment]
The build list of the EndeavourOS packages is in file
https://github.com/endeavouros-team/eos-pkgbuild-setup/blob/main/assets.conf.mirrors.mirror1#L108
in array variable `PKGNAMES`. Package names with suffix `/aur` means they will be taken from the AUR.

Today I made small changes to the PKGBUILD files of some EndeavourOS packages. Please let me know if there still are something that's not working.

**Comment by hlein** [comment]
> The build list of the EndeavourOS packages is in file https://github.com/endeavouros-team/eos-pkgbuild-setup/blob/main/assets.conf.mirrors.mirror1#L108 in array variable `PKGNAMES`. Package names with suffix `/aur` means they will be taken from the AUR.
> 
> Today I made small changes to the PKGBUILD files of some EndeavourOS packages. Please let me know if there still are something that's not working.

Aha perfect thank you! I think that's the last piece I couldn't find.
