### ISSUE TITLE
ckbcomp pkgver resolution fails due to HTML change at salsa.debian.org

### ISSUE THREAD

**Issue by hlein** [endeavouros-team/PKGBUILDS#336]
`makepkg` for `chkbcomp/PKGBUILD` errors out at the moment with:
`==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.`

This is because of an HTML change at `salsa.debian.org` that causes `pkgver` to extract incorrectly.

In `PKGBUILD`, `_ckbcomp_preparations` does the following to extract the latest package version:
```
    local site="https://salsa.debian.org"

    url="$site/installer-team/console-setup"

    local data=$(curl --fail --silent --location --max-time 10 $url/-/tags)
    local dl="$site$(echo "$data" | grep '"nofollow" download' | grep \.tar\.gz | head -n1 | sed -e 's|.* href="||' -e 's|".*||')"

    pkgver=$(echo "$dl" | sed -E 's|.*/([0-9\.]+)/.*|\1|')
```
The problem is that download links no longer contain `"nofollow"`, so the processing of `$data` returns nothing, `$dl` becomes just the contents of `$site`, or `https://salsa.debian.org`, and `pkgver` ends up set to that same string.

If I just simplify to `grep 'download'` this case works[*].

[*] At the moment I occasionally get 500 errors from `salsa.debian.org` but AFAIK that is a temporary them problem.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/PKGBUILDS/blob/master/ckbcomp/PKGBUILD
we should review it indeed @manuel-192 @dalto8

**Comment by manuel-192** [comment]
Thanks for the bug report!
We use only file /usr/bin/ckbcomp from this package, and it has not changed since package version 1.223 which is the latest package version in the EndeavourOS repo.

We'll fix this as soon as possible.

**Comment by manuel-192** [comment]
ckbcomp is fixed now.
