### ISSUE TITLE
[nvidia-inst] wrong modeset

### ISSUE THREAD

**Issue by Madic-** [endeavouros-team/PKGBUILDS#342]
The script sets in /etc/default/grub the kernel parameter nvidia-drm.modeset=1

But it should be nvidia_drm.modeset=1 (at least for >=550, maybe that changed to the underscore?)

https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

**Comment by manuel-192** [comment]
It can contain either '-' or '_'.
https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html
