### ISSUE TITLE
eos-qogir-icons is outdated

### ISSUE THREAD

**Issue by MartinX3** [endeavouros-team/PKGBUILDS#347]
See https://github.com/endeavouros-team/PKGBUILDS/tree/master/eos-qogir-icons

New version is
https://github.com/vinceliuice/Qogir-icon-theme/releases/tag/2023-06-05

Maybe that's the reason for
https://github.com/vinceliuice/Qogir-icon-theme/issues/128

Since I use EOS there is no difference switching between Qogir and Qogir-dark.

![image](https://github.com/user-attachments/assets/d5b3ba25-5bf3-4652-94c1-da4c593d3be0)

![image](https://github.com/user-attachments/assets/0d33bdb3-4c4a-4d2a-95ff-f392da292287)

**Comment by manuel-192** [comment]
Thanks! Updated `eos-qogir-icons` to version 6-1 which now uses upstream version 2023-06-05.

**Comment by MartinX3** [comment]
@manuel-192 Thank you!
Sadly there is still no difference between the light and dark variant in the task bar.
Is it only compatible with a dark task bar?

**Comment by killajoe** [comment]
issue seems that we do not have Qogir-Light in the build ?
![2024-12-30_00-35](https://github.com/user-attachments/assets/c240476a-2385-42b5-94ca-9e4b38d61bf1)
https://github.com/vinceliuice/Qogir-icon-theme/blob/9e2fec63827d2159e204b768e926f0cb707dfb80/install.sh#L19
`COLOR_VARIANTS=('' '-Light' '-Dark')`
On EndeavourOS PKGBUILD we do see: COLOR_VARIANTS=('' '-dark') insid ethe patch we use.
I will recreate the patch and test.

**Comment by killajoe** [comment]
> Is it only compatible with a dark task bar?

Current state (release) uses symlinking to the same icons for the dark and non-dark variants.
Next release will include the light version that will add black symbolic icons for light theming. 
You can try using the git version from AUR:

` yay -Rdd eos-qogir-icons` 
` yay -S qogir-icon-theme-git` 

But be careful with -Rdd .. it ignores dependencies.. and eos-welcome  is depending on eos-qogir-icons

**Comment by MartinX3** [comment]
Setting the theme to "Arc-Lighter", the panel background style to "use system style" and deactivating the dark mode of the panel together with the "Qogir-Light" symbols it looks much more readable.

The "Qogir" symbols are a mix of "Dark" and "Light" it seems.

But some of the symbols which are now darker and visible have a weak contrast.
Is this the case because the theme is "Arc-Lighter" and the Symbols are "Qogir-Light" and "Arc" and "Qogir" are simply not fully compatible?

"Arc-Lighter" & "Qogir-Light"
![image](https://github.com/user-attachments/assets/12014d97-e9e5-4977-b0d7-ea67d38d62dd)

Or is probably the "Arc-Light" theme also missing?
![image](https://github.com/user-attachments/assets/817932a0-1967-4cea-8d5b-cf7b07e7908c)

And are "Qogir-Lighter" and "Qogir-Darker" also missing or are the "*er" variants just a "Arc" thing?

**Comment by killajoe** [comment]
GTK theme and icons are not mixed or related directly.. icon sets do not really interfere with the GTK-theme.
But indeed you can use what ever fits your needs. We do only provide a basic setup.
arc and qogir are easy to handle and providing full icon set including cursor with it.  

Package size is also a thing. 
And we do use qogir icons with the EndeavourOS apps too.

May one day we will change if it is needed. For now we will see the fix with the next release of qogir icons. Or we could switch to use git commit as source.
