### ISSUE TITLE
German translation: some notes

### ISSUE THREAD

**Issue by taschenlampe** [endeavouros-team/PKGBUILDS#38]
Hi!

Some little findings that I see in  commit e3c796d87e59288dcc2eb616bb35a916a4c79074:

from "ins_text              "Installiere EndeavourOS aud deiner Festplatte!"
to  "Installiere EndeavourOS **auf deine** Festplatte!" or "EndeavourOS auf deine Festplatte installieren!"

from ns_starttip          "Starte den EndeavourOS Installer zusammen mit der Terminal Ausgabe"
to "Starte den EndeavourOS Installer zusammen mit der **Terminalausgabe**"

from ins_keys              "Initialisiere Pacman Schlüssel"
to "Initialisiere Pacman-Schlüssel"

from ins_keystip           "Initialisiere die von Pacman benötigten Schlüssel Dateien"
to "Initialisiere die von Pacman benötigten **Schlüsseldateien**"

from ins_reltip            "MehrInformationen zur neusten Veröffentlichung"
to "Mehr Informationen zur neusten Veröffentlichung"

ins_tips              "Installations Tipps" / ins_tipstip           "Installations Tipps"
to "Installationstipps"

from ins_troubletip        "System Rettung"
to "Systemrettung"

**Comment by manuel-192** [comment]
Thanks! Your changes have been merged.
And sorry about this late reply.
