### ISSUE TITLE
grub-tools doesn't work if "grub-silent aur" is installed

### ISSUE THREAD

**Issue by mireiner** [endeavouros-team/PKGBUILDS#70]
https://aur.archlinux.org/packages/grub-silent/

grub-silent is a grub substitute to get rid of the "Welcome to grub" message at the begin of the grub boot sequence. It is particularly useful if a grub theme is installed. Then this short flickering up "Welcome to grub" message can be annoying before the grub theme shows up.

If grub-silent aur is installed on EndeavourOS then an grub update will lead to a corrupt grub.cfg file and no os-prober menuentry will start anymore. The corrupted line in /boot/grub/grub.cfg is:

initrd /boot/intel-ucode.img^/boot/initramfs-linux.img

Instead of an empty space character there's a "^" character in the middle of the line that isn't correct.

Tested with:
EndeavourOS 2020.09.20 release installed in german language (don't know if this is relevant)

**Comment by killajoe** [comment]
we do handle BUGS here:
https://forum.endeavouros.com/c/Arch-based-related-questions/bug-reports/64
i crosslink it to track this:
https://forum.endeavouros.com/t/grub-tools-doesnt-work-if-grub-silent-aur-is-installed/9804

**Comment by manuel-192** [comment]
Closing as this was answered on the linked EndeavourOS forum.
