### ISSUE TITLE
nVidia RTX 30xx missing from DB 

### ISSUE THREAD

**Issue by akej74** [endeavouros-team/PKGBUILDS#72]
I noticed that "nvidia-installer-check" failes for my RTX 3090; id's for this new series of cards may be missing from the DB. Id for the 3090 is "2204".

**Comment by killajoe** [comment]
the db is taken from nvidia directly, may you need to update it?

`nvidia-installer-update-db`

**Comment by akej74** [comment]
Thanks for the suggestion, `nvidia-installer-update-db` did update the DB as follows:
```
Fetching NVIDIA graphics card ids from nvidia.com ...
Adding NVIDIA graphics card ids to the local database.
```
But still, the problem with `nvidia-installer-check` persists:
```
Sorry, your Nvidia card (id: 2204) is not supported by nvidia-dkms nor nvidia-390xx-dkms.
```
Anything else I can check on my side...?

**Comment by manuel-192** [comment]
Sorry about late answer.
You can try forcing the installing the nvidia-dkms package and see if it works now. If it doesn't, best to wait for the next nvidia-dkms package update.

**Comment by manuel-192** [comment]
Found a bug in nvidia-installer-update-db. Now the nvidia-installer-check should work OK.
Thanks for reporting!

**Comment by akej74** [comment]
Thanks for the update, I can confirm nvidia-installer-update-db and nvidia-installer-check now works for my RTX 3090.
