### ISSUE TITLE
KDE-Plasma installs missing endeavouros-logo files

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/PKGBUILDS#73]
https://github.com/endeavouros-team/PKGBUILDS/blob/master/endeavouros-theming/PKGBUILD

after updated kde it uses "distroname"-logo.png and "distroname"-logo.svg files to show inside kde settings about slide on kde plasma installs. 
![kde-screenshot](https://i.imgur.com/s476Zt4.png)
Before it was only "distroname".png/svg

**Comment by manuel-192** [comment]
Symlinks were added, closing.
