### ISSUE TITLE
eos-update-notifier forces the usage of yay while paru is optional

### ISSUE THREAD

**Issue by MartinX3** [endeavouros-team/PKGBUILDS#76]
Dear development team,

I recently saw, that it supports paru and I migrated to it.
Sadly, i can't remove yay or the `eos-update-notifier` will be removed as well, since it is a hard dependency.

As far as I know paru is the official successor of yay since the main developer left yay to rewrite yay in rust and name it paru with more features and 100% yay compatibility.

But using paru and yay on the same computer bloats the storage space, since both have their own git cache in /home/$HOME/.cache/{paru|yay}

**Comment by manuel-192** [comment]
Thanks for the report!
As yay has been the default AUR helper in EndeavourOS, we didn't make it an optional dependency originally. But now, as paru is available, it seems more sensible to do so.
The next version of eos-update-notifier will have it as optional.
