### ISSUE TITLE
Add Flatpak update to the updater?

### ISSUE THREAD

**Issue by mkellyxp** [endeavouros-team/PKGBUILDS#80]
I love using the EOS updater, but find myself always having to then separately  run "flatpak update".  

Is there a way to optionally add flatpak update to the EOS updater like the AUR is?

I'm happy to try and add this code myself, but I'm a little lost on where exactly the update is happening.

**Comment by manuel-192** [comment]
Thanks for the interesting comment!
I have been thinking about adding support for this, but so far it is not implemented.
But now I'll give this some more thought.

This is the current plan: user may create a program (preferably a small bash script) that the EOS updater calls if it exists. Here I call it the _additional updater_.

So, here's what you should do or assume for the additional updater:
- In file **/etc/eos-update-notifier.conf** add a value to variable **AdditionalEosUpdater**: the name of the additional updater the EOS updater calls.
- The additional updater gets the log file name as the parameter and can write (append!) to that if needed.
- The additional updater must return the exit code 0, 1, or 2 like 'checkupdates'.
- Internally the additional updater should handle everything flatpak updating requires, like showing the operation to the user.

I'm already implementing this, so if you have comments, please be quick! ;-)

**Comment by manuel-192** [comment]
Now I added the new code to version 1.12-1 of eos-update-notifier. It is not released as a package yet, it is only on the PKGBUILDS here at github.
Please try it and report if it works for you. And any comments on improving it are appreciated.

**Comment by mkellyxp** [comment]
This is a great solution, thank you!  I'm a bit confused, where does the actual update happen?  Looking at it, it seems this is just a notifier?   Where is the actual "UpdateInTerminal"?  I'm unsure of how to test this.

Although i'm a web developer and familiar with GIT, i'm new to THIS type of development and open source, so apologies on not fully understanding how this all works.

I'm happy to share my flatpak script as well.  Just let me know where to share it once I have it tested and working.  Thanks again.  I'm really wanting to help with the project in any way

**Comment by manuel-192** [comment]
Everything related to flatpak should happen inside your $AdditionalEosUpdater program. Eos-update-notifier simply calls your script after checking other updates, but does nothing else (except check your exit code).
You can use e.g. RunInTerminal or yad or any other tool if needed inside your script to show the user what is happening.

So basically your script should at least do:
- call flatpak update (maybe in RunInTerminal ??)
- return 0 if flatpaks had updates
- return 1 if some failure occurred
- return 2 if no flatpak updates were available

The return code (0-2) is used by the eos-update-notifier to see if the **No updates available** window should be given or not.
If any updates happened (in Arch/EOS/AUR or your flatpak), then this window is not shown.

Testing is easy, simply run eos-update-notifier in the terminal.

**Comment by manuel-192** [comment]
One question for you: are you referring to the **eos-update-notifier** or **UpdateInTerminal**?
They are two very different programs, and suddenly I'm not sure which one you are referring.

**Comment by mkellyxp** [comment]
Ahhh, yeah, I was talking about actually DOING the updates.  How does that happen?  The notification is cool, but really i just want to be able to call a flatpak update when I'm doing the eos-updates.  I was unsure of where UpdateInTerminal was.  I assumed it was linked in here somewhere.. but perhaps not

**Comment by manuel-192** [comment]
UpdateInTerminal is a command that does the update when user runs it.

eos-update-notifier is a more complex program. It
- periodically checks for updates (as a service) and notifies user when updates are available
- allows user to do the actual update too, so no separate updater is required

**Comment by manuel-192** [comment]
https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-bash-shared/UpdateInTerminal

Note that I did the new changes to another program at:
https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-update-notifier/eos-update-notifier

**Comment by mkellyxp** [comment]
Ahhh thank you for that.. i was wondering where the actual script was.. now I see it.

I'll test out the notifier too.. thanks so much!
