### ISSUE TITLE
lsb_release should set the distro codename

### ISSUE THREAD

**Issue by nergdron** [endeavouros-team/PKGBUILDS#83]
just had a nice discussion with folks on Telegram, talking about how `lsb_release` on EOS doesn't set the lsb codename, which breaks some automation and other tools. per the lsb docs, codename should get set:

```
-c, --codename     

displays codename according to distribution release. The output is a single line of text of the following format.

Codename:\t<Codename>
```

something like "rolling", or the timestamp of the last pacman update, should be sufficient to keep this from breaking things.

**Comment by killajoe** [comment]
hi again, thanks for bringing this up, i do link this one to the forum, where we discuss BUGS.
https://forum.endeavouros.com/t/open-lsb-release-should-set-the-distro-codename/11854

**Comment by manuel-192** [comment]
Thanks! Joe's pull request merged.
