### ISSUE TITLE
Why is pahis using a PAGER?

### ISSUE THREAD

**Issue by mabod** [endeavouros-team/PKGBUILDS#94]
I find it really inconvenient that pahis is using a pager. When I close the pager I do not see the output of the pahis command anymore. I do not have any trace of pahis output when I scroll back in my terminal window. This is inconvenient from my point of view.

If I wanted to use a pager I could do this on my own by piping the pahis output to a pager. There is not need for pahis to force a pager on me. 

I believe pahis should better print the output directly to the terminal. Or at least provide a command line option to turn off the pager.

**Comment by manuel-192** [comment]
Thanks for the comment!

This can be quite easily worked around already, e.g.
pahis | tee /dev/null

But I'm adding an option --no-pager which causes pahis not to use pager.
